version: "3.8"

services:
  sell-project:
    build: .
    image: ${DOCKER_USERNAME}/sell-project:latest
    container_name: sell-project
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    mongo:
      image: mongo:7
      container_name: mongo
      ports:
        - "27017:27017"
    app:
      build: .
      environment:
        MONGO_URI: mongodb://165.22.157.32:27017/crud_products
      depends_on:
        - mongo
